### ISSUE TITLE
Pre CreateProject to identify any items that won't be written.

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#121] opened 2018-10-28 16:57 UTC
A way to run CreateProject, or similar, to report items that present issues writing the project to disk before actually doing it.

**Comment by PhilLast** [comment] 2018-10-28 23:49
Something like - ?
```
      ]exceptions #.space
uncanonical fns:
#.space.f00 ...
unnamed spaces:
#.space.ns ...
unrenderable arrays:
#.space.A ...
```
The first two categories are easy to find. The third might require the prior attempt but all the code exists.

**Comment by PhilLast** [comment] 2018-10-29 07:43
Re. this and the other two related issues. 
Perhaps the first thing would be for acre to avoid throwing the error and trap for the encoding of individual items that cause it as is done for decoding on opening. There is always the possibility that something not previously encountered may crop up.
Possibly this a.m..

Then an Exclusion (or what-have-you) command possibly after tea this p.m..

**Comment by PhilLast** [comment] 2018-10-30 14:40
Or maybe not.

Easiest, and current new plan, possibly temporary, is to pop up a window showing everything acre will _not_ attempt to save: unnamed spaces, derived fns, GUI objects &c. and if any items fail to format: arrays containing ⎕ORs &c. to pop up another window saying just that.

**Comment by PhilLast** [comment] 2018-10-30 16:45
Committed. 
CaseCode and KeepHistory now default to 'Off' for a new project. Call CreateProject with the -casecode='on' flag to reverse that.
Either can still be edited in the config file and will take effect at the following OpenProject.
CreateProject will now pop up windows giving the names and ⎕NC of all items NOT saved in the project whether by design or error.
APLAN is now capable of encoding and decoding arrays containing ⎕NULLs 'though not ⎕ORs or ⎕UCS 0.
But now prohibits the evaluation of expressions containing unquoted characters other than '[(←⍴,⊂⋄/⍬⎕)]', ⎕D and name chars.

**Closed** 2019-03-05 13:16 UTC
Labels: enhancement
